name: Deploy to GitHub Pages
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        REACT_APP_THEME: ${{ secrets.REACT_APP_THEME }}
        REACT_APP_TODO_LIST: ${{ secrets.REACT_APP_TODO_LIST }}
        CI: false

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: main
